tab_signin_id = '//*[@id="header"]/div[2]/div/div/nav/div[1]/a'
enter_email_id = '//input[@id = "email_create"]'
button_create_id = '//button[@id = "SubmitCreate"]'

# Bài tập 02 :
#tab_signin_id = '//div[@class="header_user_info"]'
#email_textbox_id = '//input[@id="email_create"]'
#button_create_account_id = '//button[@id="SubmitCreate"]'
# CREATE AN ACCOUNT
# YOUR PERSONAL INFORMATION
radio_Mr_id = '//input[@id="id_gender1"]'
radio_Mrs_id = '//input[@id="id_gender2"]'
first_name_inf_textbox_id = '//input[@id="customer_firstname"]'
last_name_inf_textbox_id = '//input[@id="customer_lastname"]'
password_txt_id = '//input[@id="passwd"]'
date_birth_id = '//select[@id="days"]'
days_value_id = '//select[@id = "days"]//option[@value = "2"]'
month_birth_id = '//select[@id="months"]'
month_value_id = '//select[@id="months"]//option[@value = "2"]'
years_birth_id = '//select[@id="years"]'
years_value_id = '//select[@id="years"]//option[@value = "2018"]'
signup_newsletters_id = '//input[@id="newsletter"]'
# YOUR ADDRESS
first_name_addr_id = '//input[@id="firstname"]'
last_name_addr_id = '//input[@id="lastname"]'
company_textbox_id = '//input[@id="company"]'
address_txt_id = '//input[@id="address1"]'
city_txt_id = '//input[@id="city"]'
select_state_id = '//select[@id="id_state"]'
value_state_id = '//select[@id="id_state"]//option[@value = "1"]'
zip_code_id = '//input[@id="postcode"]'
country_txt_id = '//select[@id="id_country"]'
value_country_id = '//select[@id="id_country"]//option[@value = "21"]'
additional_inf_id = '//textarea[@id="other"]'
home_phone_id = '//input[@id="phone"]'
mobile_phone_id = '//input[@id="phone_mobile"]'
address_alias_id = '//input[@id="alias"]'
button_registration_id = '//button[@id="submitAccount"]'

